### ISSUE TITLE
The gamutrF fails to connect to the BladerF

### ISSUE THREAD

**Issue by liuyueboye** [IQTLabs/gamutRF#403]
Hello, how does GamuTRf connect to Bladerf? Bladerf is running correctly on the VM. Run the "docker run -v/TMP :/ TMP -ti iqtlabs/gamutrf gamutrf-scan -- SDR bladerf "command to return "[ERROR] bladerf_open_with_devinfo() Returned -7 - No device(s) available" Please see the screenshot for details 
![bladerf_info](https://user-images.githubusercontent.com/19701831/189871677-a611c146-80c1-4d06-964c-89b886ed333e.png)
![gamutrf-scan](https://user-images.githubusercontent.com/19701831/189871685-2f007821-597d-46a7-9795-3035d98df19c.png)
![gamutrf-scan_freq](https://user-images.githubusercontent.com/19701831/189871688-9ba4ae33-7654-4e79-a048-0a4090a10cd0.png)
![system_version](https://user-images.githubusercontent.com/19701831/189871693-6bb91f89-64a5-4d23-82d5-d6761c941470.png)

**Comment by cglewis** [comment]
@liuyueboye the docker container also needs capabilities added and the device mounted when run. Try adding these flags from the docker-compose file (`orchestrator.yml`):

```
    cap_add:
      - SYS_NICE
      - SYS_RAWIO
    devices:
      - /dev/bus/usb:/dev/bus/usb
```

```
docker run --device=/dev/bus/usb:/dev/bus/usb --cap-add=SYS_NICE --cap-add=SYS_RAWIO -v /tmp:/tmp -ti iqtlabs/gamutrf gamutrf-scan --sdr bladerf
```
